package Principal;

import javax.swing.JOptionPane;

public class Principal extends javax.swing.JFrame {

    public Principal() {
        initComponents();
    }

    /**
     * e This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(656, 700));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(jDesktopPane1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));
        jDesktopPane1Layout.setVerticalGroup(jDesktopPane1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 787, Short.MAX_VALUE));

        jLabel1.setIcon(new javax.swing.ImageIcon(
                "C:\\Users\\Hernan\\Documents\\NetBeansProjects\\SistemaExperto\\Resources\\7.jpg")); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jMenu1.setText("Consulta");

        jMenuItem1.setText("¿Que sintomas tiene?");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jDesktopPane1)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        // String Sintoma =JOptionPane.showInputDialog("¿ Sintoma que Padece \n?"+
        // "Fatiga Extrema");
        int Sintoma = Integer.parseInt(JOptionPane.showInputDialog(null,
                "Selecciona con el numero tu sintoma\n" + "1.-Fatiga Extrema\n " + "2.-Dolor de Cabeza\n"
                        + "3.-Fiebre\n" + "4.-Dolor de Estomago\n" + "5.-Dificultad Respiratoria\n" + "6.-Tos\n"));
        if (Sintoma <= 10) {
            JOptionPane.showMessageDialog(null, "Seleccionaste el numero " + Sintoma);
            if (Sintoma == 1) {
                int edad = Integer.parseInt(JOptionPane.showInputDialog(null, "Coloca tu edad"));
                int signos = Integer.parseInt(JOptionPane.showInputDialog(null, "Sintoma o signos estan asociados"
                        + "a su motivo de consulta ? \n" + "1.-Debilidad\n" + "2.-Dolor de Cabeza\n"));
                int debilidad = Integer.parseInt(JOptionPane.showInputDialog(null,
                        "La Actividad Fisica le provoca " + "mucha Fatiga ??\n" + "1.-Si\n" + "2.-No"));
                int secansa = Integer
                        .parseInt(JOptionPane.showInputDialog(null, "Se cansa Facilmente mas de lo habitual "
                                + "para la misma intesidad de ejercicio ?\n" + "1.-Si\n" + "2.-No"));
                int sensacion = Integer.parseInt(JOptionPane.showInputDialog(null,
                        "La sensacion de cansansio dura " + "desde hace meses?\n" + "1.-Si\n" + "2.-No"));
                int Lafatiga = Integer.parseInt(JOptionPane.showInputDialog(null, "La fatiga le obliga a permanecer en "
                        + "el mismo domicilio la mayor parte?\n" + "1.-Si\n" + "2.-No"));
                if (signos == 1 && debilidad == 1 && secansa == 1 && sensacion == 1 && Lafatiga == 1) {
                    JOptionPane.showMessageDialog(null,
                            "RESULTADO \n" + "Consulte a un Especialista importante descartar\n"
                                    + "Patologias mas graves: insuficiencia Cardiaca.\n\n" + "Enfermedades:\n"
                                    + "Sindrome de Fatiga Cronica. Medicina interna, Neurologia");
                } else if (signos == 1 && debilidad == 2 && secansa == 2 && sensacion == 2 && Lafatiga == 2) {
                    JOptionPane.showMessageDialog(null, "Usted no padece nada grave");
                } else if (signos == 2 && debilidad == 2 && secansa == 2 && sensacion == 2 && Lafatiga == 2) {
                    JOptionPane.showMessageDialog(null, "Usted no padece nada grave");
                } else if (signos == 1 && debilidad == 1 && sensacion == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Es una alteración de la función cardíaca en \n "
                                    + "la cual el corazón pierde total o parcialmente\n"
                                    + "su capacidad para bombear sangre al resto del\n"
                                    + "cuerpo puedo recomendarle cambios en el estilo \n"
                                    + "de vida, como dejar de fumar, evitar el sobrepeso,\n"
                                    + "control de la tensión arterial\n");
                } else if (signos == 1 && secansa == 1 && Lafatiga == 1) {
                    JOptionPane.showMessageDialog(null, "No se alcanzó ningún prediagnóstico \n"
                            + "se debe solo a falta de ejercicio fisico!!! \n");
                } else if (signos == 1 && debilidad == 1 && secansa == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Acuda a un hospital lo antes posible.\n" + "Asistencia médica necesaria!!! \n");
                } else if (signos == 1 && secansa == 1 && sensacion == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Los principales síntomas son palidez, cansancio y sensación \n"
                                    + " subjetiva de falta de aire. El tratamiento puede consistir en \n "
                                    + " cambios alimentarios, suplementos nutricionales, tratamiento \n"
                                    + "médico y/o quirúrgico, y transfusión de sangre.\n");
                } else if (signos == 2 && debilidad == 1 && secansa == 1) {
                    JOptionPane.showMessageDialog(null,
                            "La cefalea banal suele presentarse con dolor de cabeza\n"
                                    + "sin otros síntomas acompañantes Puede ser intermitente y \n"
                                    + "empeorar con  ciertos movimientos y/o cambios ambientales.\n"
                                    + "Es recomendable buscar ambientes en calma con poca luz y poco\n"
                                    + " ruido para favorecer la recuperación.");
                } else if (signos == 2 && secansa == 1 && sensacion == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Acuda a un hospital lo antes posible.\n" + "Asistencia médica necesaria.Puede ser \n "
                                    + "intermitente y empeorar con ciertos movimientos \n "
                                    + "y/o cambios ambientales. ");
                } else if (signos == 2 && debilidad == 1 && Lafatiga == 1) {
                    JOptionPane.showMessageDialog(null, "Acuda a un hospital lo antes posible.\n"
                            + "la aspirina y el Paracetamol pueden ser un calmante.");
                } else if (signos == 2 && secansa == 1 && Lafatiga == 1) {
                    JOptionPane.showMessageDialog(null, "Debes tomar ibuprofeno, paracetamol o aspirina  ");
                } else if (signos == 2 && debilidad == 1 && sensacion == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Debes Acudir a un especialista para medicarte \n" + "lo mas pronto posible.");
                } else {
                    JOptionPane.showMessageDialog(null, "El dolor es temporal de no ser asi consulte su medico !!!");
                }
                // termina la seleccion 1
            } else if (Sintoma == 2) {
                int edad = Integer.parseInt(JOptionPane.showInputDialog(null, "Coloca tu edad"));
                int signos = Integer.parseInt(JOptionPane.showInputDialog(null, "Indique la intensidad de dolor\n"
                        + "1:- de 1-3: Bajo\n" + "2:- de 1-5: Medio\n" + "3:- de 1-10: Alto"));// Seleccione
                int aparece = Integer.parseInt(
                        JOptionPane.showInputDialog(null, "El dolor aparece bruscamente\n" + "1.- Si\n" + "2.- No\n"));
                int calma = Integer.parseInt(JOptionPane.showInputDialog(null,
                        "¿Calma el dolor de cabeza con analgésicos habituales?\n" + "1.- Si\n" + "2.- No\n"));
                int empezo = Integer.parseInt(JOptionPane.showInputDialog(null,
                        "¿Ha empezado el dolor de cabeza mientras realizaba un ejercicio intenso?\n" + "1.- Si\n"
                                + "2.- No\n"));
                if (signos == 1 && aparece == 1 && calma == 1 && empezo == 1) {
                    JOptionPane.showMessageDialog(null, "Consulte con un especialista.\n"
                            + "El diagnóstico es clínico, mediante interrogatorio y exploración física.\n"
                            + "En el momento inicial es recomendable permanecer estirado y en reposo.\n"
                            + "Se debe tratar la migraña lo antes posible. El tratamiento se basa en el \n"
                            + "uso de antiinflamatorios no esteroideos (ibuprofeno, naproxeno, etc), triptanes\n"
                            + "(sumatriptán, rizatriptan, etc) y/o ergotamina.");
                } else if (signos == 1 && aparece == 2 && calma == 2 && empezo == 2) {
                    JOptionPane.showMessageDialog(null, "No se encontraron sintomas");
                } else if (signos == 2 && aparece == 2 && calma == 2 && empezo == 2) {
                    JOptionPane.showMessageDialog(null, "No se encontraron sintomas");
                } else if (signos == 3 && aparece == 2 && calma == 2 && empezo == 2) {
                    JOptionPane.showMessageDialog(null, "No se encontraron sintomas");
                } else if (signos == 1 && aparece == 1 && calma == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Debes Acudir a un especialista para medicarte \n" + "lo mas pronto posible.");
                } else if (signos == 1 && calma == 1 && empezo == 1) {
                    JOptionPane.showMessageDialog(null, "Se utilizarán medicamentos antivertiginosos solos o en\n"
                            + " combinación con benzodiacepinas para reducir la sensación rotatoria.");
                } else if (signos == 1 && aparece == 1 && empezo == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Cefalea tensional\n" + "Es desencadenado por estrés, depresión o ansiedad.\n"
                                    + "El tratamiento con analgésicos habituales de venta libre,\n"
                                    + "suele ser suficiente para controlar el dolor.\n"
                                    + "En casos más severos o persistentes se pueden asociar relajantes\n"
                                    + "musculares y ansiolíticos, pero requieren prescripción médica.");
                } else if (signos == 2 && aparece == 1 && calma == 1) {
                    JOptionPane.showMessageDialog(null,
                            " El tratamiento se basa en el uso de\n"
                                    + " antiinflamatorios no esteroideos (ibuprofeno, naproxeno, etc), \n"
                                    + "triptanes (sumatriptán, rizatriptan, etc) y/o ergotamina.");
                } else if (signos == 2 && calma == 1 && empezo == 1) {
                    JOptionPane.showMessageDialog(null,
                            " El tratamiento se basa en el uso de\n"
                                    + " antiinflamatorios no esteroideos (ibuprofeno, naproxeno, etc), \n"
                                    + "triptanes (sumatriptán, rizatriptan, etc) y/o ergotamina.");
                } else if (signos == 2 && aparece == 1 && empezo == 1) {
                    JOptionPane.showMessageDialog(null,
                            " Es un dolor de cabeza intenso producido por\n"
                                    + " cambios en el calibre de los vasos sanguíneos craneales. La migraña\n"
                                    + " es la segunda causa más común de dolor de cabeza");
                } else if (signos == 3 && aparece == 1 && calma == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Dolor de cabeza muy intenso con afectación del nervio\n"
                                    + " trigémino, que afecta típicamente a un lado del cráneo."
                                    + "se recomienda cuando el dolor es muy severo, acudir a un \n"
                                    + "centro médico para confirmar el diagnóstico y reforzar el\n"
                                    + "tratamiento con oxígeno.");
                } else if (signos == 3 && calma == 1 && empezo == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Dolor de cabeza muy intenso con afectación del nervio\n"
                                    + " trigémino, que afecta típicamente a un lado del cráneo."
                                    + "se recomienda cuando el dolor es muy severo, acudir a un \n"
                                    + "centro médico para confirmar el diagnóstico y reforzar el\n"
                                    + "tratamiento con oxígeno.");
                } else if (signos == 3 && aparece == 1 && calma == 1) {
                    JOptionPane.showMessageDialog(null,
                            "se recomienda cuando el dolor es muy severo, acudir a un \n"
                                    + "centro médico para confirmar el diagnóstico y reforzar el\n"
                                    + "tratamiento con oxígeno.");
                } else if (signos == 3 && empezo == 1) {
                    JOptionPane.showMessageDialog(null,
                            "se recomienda cuando el dolor es muy severo, acudir a un \n"
                                    + "centro médico para confirmar el diagnóstico y reforzar el\n"
                                    + "tratamiento con oxígeno.");
                } else {
                    JOptionPane.showMessageDialog(null, "El dolor es temporal de no ser asi consulte su medico !!!");
                }

            } else if (Sintoma == 3) {
                int edad = Integer.parseInt(JOptionPane.showInputDialog(null, "Indica tu edad"));
                int presenta = Integer
                        .parseInt(JOptionPane.showInputDialog(null, "¿Presenta fiebre prolongada?\n" + "1:- Si\n" // Seleccion
                                + "2:- No\n"));
                int fiebre = Integer
                        .parseInt(JOptionPane.showInputDialog(null, "¿Ha tenido fiebre durante 1 semana?\n" + "1.- Si\n" // Seleccion
                                + "2.- No\n"));
                int suda = Integer.parseInt(JOptionPane.showInputDialog(null,
                        "¿Coincidiendo con la fiebre está sudando mucho?\n" + "1.- Si\n" // Seleccion
                                + "2.- No\n"));
                int dolor = Integer
                        .parseInt(JOptionPane.showInputDialog(null, "¿¿Tiene dolor de cabeza??\n" + "1.- Si\n" // Seleccion
                                + "2.- No\n"));
                if (presenta == 1 && fiebre == 1 && suda == 1 && dolor == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Es primordial asegurar una correcta hidratación por vía oral,\n"
                                    + " o en su defecto por vía intravenosa. Se tratará la infección bacteriana\n"
                                    + " con antibiótico.  La infección se produce al ingerirse alimentos y bebidas\n"
                                    + " contaminadas con productos fecales humanos.");
                } else if (presenta == 1 && fiebre == 2 && suda == 2 && dolor == 2) {
                    JOptionPane.showMessageDialog(null, "No se encontraron sintomas");
                } else if (presenta == 2 && fiebre == 2 && suda == 2 && dolor == 2) {
                    JOptionPane.showMessageDialog(null, "No se encontraron sintomas");
                } else if (presenta == 1 && fiebre == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Debes Acudir a un especialista para medicarte \n" + "lo mas pronto posible.");
                } else if (suda == 1 && dolor == 1) {
                    JOptionPane.showMessageDialog(null, "Se recomienda tomar Theraflu en caso de emergencia\n"
                            + "ya que es una medicina combinada se usa para tratar dolor de cabeza, fiebre, \n"
                            + "dolor de cuerpo, secreción o congestión nasal, estornudos, picazón, ojos llorosos,\n"
                            + "tos y congestión sinusal causados por alergias y el resfrío común.");
                } else if (presenta == 1 && fiebre == 1 && dolor == 1) {
                    JOptionPane.showMessageDialog(null, "Si lo que tienes es fiebre propia de un estado griposo o \n"
                            + "enfermedad común, puedes probar con algún medicamento de \n"
                            + "venta libre como el paracetamol y el ibuprofeno pero requieren prescripción médica.");
                } else if (fiebre == 1 && suda == 1) {
                    JOptionPane.showMessageDialog(null,
                            " El tratamiento se basa en el uso de\n"
                                    + " antiinflamatorios no esteroideos (ibuprofeno, naproxeno, etc), \n"
                                    + "triptanes (sumatriptán, rizatriptan, etc) y/o ergotamina.");
                } else if (presenta == 1 && fiebre == 1 && suda == 1) {
                    JOptionPane.showMessageDialog(null, "Si lo que tienes es fiebre propia de un estado griposo o \n"
                            + "enfermedad común, puedes probar con algún medicamento de \n"
                            + "venta libre como el paracetamol y el ibuprofeno pero requieren prescripción médica.");
                } else if (suda == 1 && fiebre == 1 && presenta == 2) {
                    JOptionPane.showMessageDialog(null,
                            " Es un dolor de cabeza intenso producido por\n"
                                    + " cambios en el calibre de los vasos sanguíneos craneales. La migraña\n"
                                    + " es la segunda causa más común de dolor de cabeza");
                } else if (fiebre == 1 && dolor == 1 && presenta == 1) {
                    JOptionPane.showMessageDialog(null, "Consulte con un especialista.");
                } else if (fiebre == 1 && dolor == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Se considera una urgencia médica por la cual se debe consultar rápidamente\n"
                                    + " en un centro hospitalario. Entre los signos de alarma a tener en cuenta se \n"
                                    + "encuentran la hipotensión mantenida,fiebre alta persistente, escasa \n"
                                    + "cantidad de orina, alteración del nivel de conciencia.");
                } else {
                    JOptionPane.showMessageDialog(null, "Comienzo de proximas nuevas sintomas consulte su medico !!!");
                }

            } else if (Sintoma == 4) {
                int edad = Integer.parseInt(JOptionPane.showInputDialog(null, "Indica tu edad"));
                int dolor = Integer.parseInt(JOptionPane.showInputDialog(null,
                        "¿¿El dolor estomacal sucedio después de la comida??\n" + "1:- Si\n" // Seleccion
                                + "2:- No\n"));
                int boca = Integer.parseInt(JOptionPane.showInputDialog(null,
                        "¿El dolor en la boca del estómago es más intenso en 2 horas?\n" + "1.- Si\n" // Seleccion
                                + "2.- No\n"));
                int analgesico = Integer.parseInt(JOptionPane.showInputDialog(null,
                        "¿¿Ha estado tomando muchos analgésicos recientemente\n"
                                + " como aspirina, piroxicam, indometacina, diclofenaco ?\n" + "1.- Si\n" // Seleccion
                                + "2.- No\n"));
                int gastritis = Integer.parseInt(
                        JOptionPane.showInputDialog(null, "¿Anteriormente no padecia de Gastritis?\n" + "1.- Si\n" // Seleccion
                                + "2.- No\n"));
                if (dolor == 1 && boca == 1) {
                    JOptionPane.showMessageDialog(null, "El dolor es causado por la falta de higiene en los alimentos\n"
                            + "si el problema persiste consulte a su medico para analizar previa infeccion");
                } else if (dolor == 2 && boca == 2 && analgesico == 2 && gastritis == 2) {
                    JOptionPane.showMessageDialog(null, "No padece de dolor Estomacal");
                } else if (dolor == 1 && boca == 2 && analgesico == 1 && gastritis == 2) {
                    JOptionPane.showMessageDialog(null, "El sitoma es temporal se recomienda ingerir mucha agua \n"
                            + "y reposar si el problema persiste consulte a un especialista");
                } else if (boca == 1 && gastritis == 1) {
                    JOptionPane.showMessageDialog(null, "Consulte su medico lo mas pronto posible sintoma posibles\n"
                            + "Infecciones graves, ulceras gastricas, problema intestinal.");
                } else if (boca == 1 && gastritis == 1 && analgesico == 1) {
                    JOptionPane.showMessageDialog(null, "Consulte su medico lo mas pronto posible sintoma posibles\n"
                            + "Infecciones graves, ulceras gastricas, problema intestinal.");
                } else if (dolor == 1 && boca == 1) {
                    JOptionPane.showMessageDialog(null, "Para aliviar su dolor puede tomar loperamida 1 cada 8 hrs  \n"
                            + "si desde la primera toma no resulta consulte a su medico para medicarla.");
                } else if (analgesico == 1 && gastritis == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Por cuestiones de salud es importante no automedicarse\n"
                                    + "sin consentimiento de un medico- problemas severos\n"
                                    + "consulte a u medico para determinar un analisis estomacal.");
                } else if (dolor == 1) {
                    JOptionPane.showMessageDialog(null, "Repose un momento el problema se debe que\n"
                            + "al ingerir sus alimentos no lo hiso de la manera correcta");
                } else if (boca == 1) {
                    JOptionPane.showMessageDialog(null, "Consulte con su especialista para medicaciones concretas");
                } else if (dolor == 1 && boca == 1 && gastritis == 1) {
                    JOptionPane.showMessageDialog(null, "Se debe tratar la causa y administrar medicamentos \n"
                            + "para disminuir la acidez gástrica. Consulte especialista.");
                } else if (dolor == 1 && gastritis == 1) {
                    JOptionPane.showMessageDialog(null,
                            "Se debe añadir un fármaco que disminuya\n" + " la cantidad de ácido en el estómago.");
                } else {
                    JOptionPane.showMessageDialog(null, "Comienzo de proximas nuevas sintomas consulte su medico !!!");
                }

            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecciona un numero Valido");

        }
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
